# Generated by Django 3.2.12 on 2024-06-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240607_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
