# Generated by Django 3.2.12 on 2024-06-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240607_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='name',
            new_name='roles',
        ),
    ]
