# Generated by Django 3.2.12 on 2024-06-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_roles_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='roles',
            new_name='name',
        ),
        migrations.AddField(
            model_name='roles',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='myapp.Permission'),
        ),
    ]
