# Generated by Django 3.2.12 on 2024-06-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_employee_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='myapp.project'),
            preserve_default=False,
        ),
    ]
