# Generated by Django 3.2.12 on 2024-06-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20240611_0449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
