# Generated by Django 3.2.12 on 2024-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20240611_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='project_name',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
