# Generated by Django 3.2.12 on 2024-06-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_dailyreport_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='codename',
            new_name='subject',
        ),
    ]
